### ISSUE TITLE
The released I2VGen-XL model seems like a single stage model

### ISSUE THREAD

**Issue by jlia904** [ali-vilab/i2vgen-xl#49]
Hi,

Thanks for sharing the code for I2VGen-XL model. 

From closer inspection of the `unet_i2vgen.py` file, it seems to me the released I2VGen-XL model is a single stage model where it takes in both image and text at the same time, without performing two stage processing as claimed in the paper. Is this the case?

Thanks!

**Comment by Steven-SWZhang** [comment]
Yes, in this open-source project, we have only released the model for single-stage high-definition video generation that can fully preserve the content of the input image, for the convenience of academic use. As for the multi-stage video generation models, we currently do not have plans to open-source it. Thank you for your interest in our work.

**Comment by jlia904** [comment]
Hi,

Thanks for your previous answer, I am another question on the released single stage I2V model. Is it also trained with 35 million videos and 6 billion images?

Thanks!

**Comment by Steven-SWZhang** [comment]
> Hi,
> 
> Thanks for your previous answer, I am another question on the released single stage I2V model. Is it also trained with 35 million videos and 6 billion images?
> 
> Thanks!

Yes.
