### ISSUE TITLE
question about watermark

### ISSUE THREAD

**Issue by syyxsxx** [ali-vilab/i2vgen-xl#50]
will having watermarks in the dataset affect the training results？
What is the way to remove the watermark from the video？

thanks advance

**Comment by Steven-SWZhang** [comment]
In my understanding, the watermark itself does not affect the performance of the model, but it will cause the generated video to carry the same watermark. You can remove the watermark by: 1) collecting some data without watermarks and training it in combination with the data that has watermarks; 2) during training, add the prompt "with watermarks" to the data with watermarks, and do not add it to data without watermarks for training; 3) during the inference process, do not add "with watermarks" to the prompt, so you will have a certain probability of obtaining a video without watermarks. However, this is somewhat related to your data ratio and data quality. I hope this can help you.

**Comment by syyxsxx** [comment]
Sounds good
I will try it out
thanks
